import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export const feeManagementStyles = StyleSheet.create({
  scroll: { paddingBottom: 120, gap: 16 },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 22,
    padding: 16,
    gap: 14,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 14,
    elevation: 3,
  },
  inlineForm: { gap: 10 },
  toggleChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: colors.primarySoft,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
  },
  toggleChipText: { fontSize: 12, fontWeight: "800", color: colors.primary },
  addChip: {
    backgroundColor: colors.primary,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
  },
  addChipText: { fontSize: 12, fontWeight: "800", color: colors.white },
  addActions: { flexDirection: "row", alignItems: "center", gap: 12 },
  cancelBtn: { paddingVertical: 12, paddingHorizontal: 8 },
  cancelBtnText: { fontSize: 14, fontWeight: "700", color: colors.textMuted },
  cellStrong: { fontSize: 14, fontWeight: "800", color: colors.text },
  inlineInput: {
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 14,
    fontWeight: "700",
    color: colors.text,
    backgroundColor: colors.white,
  },
  amountInput: {
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    fontWeight: "800",
    color: colors.primaryDark,
    backgroundColor: colors.backgroundAlt,
    minWidth: 100,
  },
  savedVal: { fontSize: 13, fontWeight: "700", color: colors.textMuted },
  savedOn: { color: colors.accentTeal },
  dash: { textAlign: "center", color: colors.textMuted },
  badge: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  badgeActive: { backgroundColor: colors.accentTealSoft },
  badgeMuted: { backgroundColor: colors.dangerSoft },
  badgeText: { fontSize: 11, fontWeight: "800", color: colors.text },
  actions: { flexDirection: "row", gap: 4 },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: 16,
    padding: 16,
  },
  totalLabel: { fontSize: 15, fontWeight: "800", color: colors.primaryDark },
  totalHint: { marginTop: 2, fontSize: 11, color: colors.textMuted, fontWeight: "600" },
  totalVal: { fontSize: 22, fontWeight: "900", color: colors.primary },
  placeholder: {
    alignItems: "center",
    gap: 8,
    paddingVertical: 24,
    backgroundColor: colors.backgroundAlt,
    borderRadius: 16,
  },
  placeholderText: { fontSize: 13, color: colors.textMuted, fontWeight: "600", textAlign: "center" },
  classPicker: { gap: 10 },
  classPickerHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  classPickerLabel: { fontSize: 13, fontWeight: "800", color: colors.text },
  classPickerActions: { flexDirection: "row", gap: 12 },
  classPickerLink: { fontSize: 12, fontWeight: "800", color: colors.primary },
  classPickerEmpty: { fontSize: 13, color: colors.textMuted, fontWeight: "600" },
  classGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  classCheck: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    minWidth: "47%",
    flexGrow: 1,
  },
  classCheckOn: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  classCheckText: { flex: 1, fontSize: 13, fontWeight: "700", color: colors.text },
  multiHint: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.primaryDark,
    backgroundColor: colors.primarySoft,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  matrixToolbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
  },
  matrixCount: { fontSize: 12, fontWeight: "700", color: colors.textMuted },
  matrixInput: {
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
    fontWeight: "800",
    color: colors.primaryDark,
    backgroundColor: colors.surface,
    minWidth: 72,
  },
  matrixTotal: { fontSize: 13, fontWeight: "900", color: colors.primary },
  selectAllRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 4,
  },
  selectAllText: { fontSize: 13, fontWeight: "800", color: colors.primaryDark },
  matrixLoading: {
    textAlign: "center",
    paddingVertical: 24,
    fontSize: 13,
    fontWeight: "600",
    color: colors.textMuted,
  },
});
